# SPDX-FileCopyrightText: 2022 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

[hmi]
environment = "dev"
app_name = "openfmb-hmi"
log-level = "Debug" # Off, Error, Info, Debug, Trace
server_port = 32771

[nats]
dev_uri = "nats://REPLACE_HOST_IP_ADDRESS:4222"
