# SPDX-FileCopyrightText: 2022 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

version: "3.4"
services:
  udp-plug-simulator:
    image: oesinc/udp-plug-simulator
    container_name: 'oes-plug'
    command: [-c, /config/config.json]
    volumes:
      - ../plug-simulator/config.json:/config/config.json
    # Important! need to use host network
    network_mode: "host"
  adapters:    
    image: oesinc/openfmb.adapters.ext
    ports:
      - "8555:8555/udp"
      - "20000:20000"  
    expose:
      - 20000  
    volumes:
      - ./tmp:/tmp              # map to shared mem for zenoh   
      - ./adapters:/adapters        # map to adapter configurations
      - ./launcher:/launcher    # launcher configuration
    command: -c /launcher/config.yaml
    environment:
      - RUST_LOG=debug
