# SPDX-FileCopyrightText: 2022 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

version: "3.4"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
    expose:
      - 4222
  adapters:    
    image: oesinc/openfmb.adapters.ext:pre-release
    ports:
      - "8255:8255/udp"    
    volumes:
      - ./tmp:/tmp              # map to shared mem for zenoh   
      - ./adapters:/adapters        # map to adapter configurations
      - ./launcher:/launcher    # launcher configuration
    command: -c /launcher/config.yaml
    environment:
      - RUST_LOG=debug
